// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: protos/keyval.proto

package keyval

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_protos_keyval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_protos_keyval_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryRequest) Reset() {
	*x = EntryRequest{}
	mi := &file_protos_keyval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryRequest) ProtoMessage() {}

func (x *EntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryRequest.ProtoReflect.Descriptor instead.
func (*EntryRequest) Descriptor() ([]byte, []int) {
	return file_protos_keyval_proto_rawDescGZIP(), []int{1}
}

func (x *EntryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_protos_keyval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_protos_keyval_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_protos_keyval_proto protoreflect.FileDescriptor

const file_protos_keyval_proto_rawDesc = "" +
	"\n" +
	"\x13protos/keyval.proto\x12\x06keyval\"/\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\" \n" +
	"\fEntryRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\x97\x01\n" +
	"\x06Storer\x12%\n" +
	"\x03Add\x12\r.keyval.Entry\x1a\r.keyval.Entry\"\x00\x12,\n" +
	"\x03Get\x12\x14.keyval.EntryRequest\x1a\r.keyval.Entry\"\x00\x128\n" +
	"\x06Delete\x12\x14.keyval.EntryRequest\x1a\x16.keyval.DeleteResponse\"\x00B\x1dZ\x1bgithub.com/tashima42/keyvalb\x06proto3"

var (
	file_protos_keyval_proto_rawDescOnce sync.Once
	file_protos_keyval_proto_rawDescData []byte
)

func file_protos_keyval_proto_rawDescGZIP() []byte {
	file_protos_keyval_proto_rawDescOnce.Do(func() {
		file_protos_keyval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_keyval_proto_rawDesc), len(file_protos_keyval_proto_rawDesc)))
	})
	return file_protos_keyval_proto_rawDescData
}

var file_protos_keyval_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_keyval_proto_goTypes = []any{
	(*Entry)(nil),          // 0: keyval.Entry
	(*EntryRequest)(nil),   // 1: keyval.EntryRequest
	(*DeleteResponse)(nil), // 2: keyval.DeleteResponse
}
var file_protos_keyval_proto_depIdxs = []int32{
	0, // 0: keyval.Storer.Add:input_type -> keyval.Entry
	1, // 1: keyval.Storer.Get:input_type -> keyval.EntryRequest
	1, // 2: keyval.Storer.Delete:input_type -> keyval.EntryRequest
	0, // 3: keyval.Storer.Add:output_type -> keyval.Entry
	0, // 4: keyval.Storer.Get:output_type -> keyval.Entry
	2, // 5: keyval.Storer.Delete:output_type -> keyval.DeleteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_keyval_proto_init() }
func file_protos_keyval_proto_init() {
	if File_protos_keyval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_keyval_proto_rawDesc), len(file_protos_keyval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_keyval_proto_goTypes,
		DependencyIndexes: file_protos_keyval_proto_depIdxs,
		MessageInfos:      file_protos_keyval_proto_msgTypes,
	}.Build()
	File_protos_keyval_proto = out.File
	file_protos_keyval_proto_goTypes = nil
	file_protos_keyval_proto_depIdxs = nil
}
