// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/keyval.proto

package keyval

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_keyval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Record) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_proto_keyval_proto protoreflect.FileDescriptor

const file_proto_keyval_proto_rawDesc = "" +
	"\n" +
	"\x12proto/keyval.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"o\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated22\n" +
	"\x06Storer\x12(\n" +
	"\x06Append\x12\r.proto.Record\x1a\r.proto.Record\"\x00B\x1dZ\x1bgithub.com/tashima42/keyvalb\x06proto3"

var (
	file_proto_keyval_proto_rawDescOnce sync.Once
	file_proto_keyval_proto_rawDescData []byte
)

func file_proto_keyval_proto_rawDescGZIP() []byte {
	file_proto_keyval_proto_rawDescOnce.Do(func() {
		file_proto_keyval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_keyval_proto_rawDesc), len(file_proto_keyval_proto_rawDesc)))
	})
	return file_proto_keyval_proto_rawDescData
}

var file_proto_keyval_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_keyval_proto_goTypes = []any{
	(*Record)(nil),                // 0: proto.Record
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_keyval_proto_depIdxs = []int32{
	1, // 0: proto.Record.last_updated:type_name -> google.protobuf.Timestamp
	0, // 1: proto.Storer.Append:input_type -> proto.Record
	0, // 2: proto.Storer.Append:output_type -> proto.Record
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_keyval_proto_init() }
func file_proto_keyval_proto_init() {
	if File_proto_keyval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_keyval_proto_rawDesc), len(file_proto_keyval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_keyval_proto_goTypes,
		DependencyIndexes: file_proto_keyval_proto_depIdxs,
		MessageInfos:      file_proto_keyval_proto_msgTypes,
	}.Build()
	File_proto_keyval_proto = out.File
	file_proto_keyval_proto_goTypes = nil
	file_proto_keyval_proto_depIdxs = nil
}
