// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/keyval.proto

package keyval

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Storer_Append_FullMethodName = "/proto.Storer/Append"
)

// StorerClient is the client API for Storer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorerClient interface {
	Append(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Record, error)
}

type storerClient struct {
	cc grpc.ClientConnInterface
}

func NewStorerClient(cc grpc.ClientConnInterface) StorerClient {
	return &storerClient{cc}
}

func (c *storerClient) Append(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, Storer_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorerServer is the server API for Storer service.
// All implementations must embed UnimplementedStorerServer
// for forward compatibility.
type StorerServer interface {
	Append(context.Context, *Record) (*Record, error)
	mustEmbedUnimplementedStorerServer()
}

// UnimplementedStorerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorerServer struct{}

func (UnimplementedStorerServer) Append(context.Context, *Record) (*Record, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedStorerServer) mustEmbedUnimplementedStorerServer() {}
func (UnimplementedStorerServer) testEmbeddedByValue()                {}

// UnsafeStorerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorerServer will
// result in compilation errors.
type UnsafeStorerServer interface {
	mustEmbedUnimplementedStorerServer()
}

func RegisterStorerServer(s grpc.ServiceRegistrar, srv StorerServer) {
	// If the following call panics, it indicates UnimplementedStorerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Storer_ServiceDesc, srv)
}

func _Storer_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorerServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storer_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorerServer).Append(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

// Storer_ServiceDesc is the grpc.ServiceDesc for Storer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Storer",
	HandlerType: (*StorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _Storer_Append_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/keyval.proto",
}
